### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by rthille** [acg/python-cdb#5]
Any plans to make this compatible with Python3?  If it's not a heavy lift, I could probably take it on...

**Comment by pyhakr** [comment]
currently doing a py3 conversion of private automation system and willing to help out.

**Comment by glensc** [comment]
is this error related to lack of python3 support?


```
✖ pip install python-cdb
Collecting python-cdb
  Using cached python-cdb-0.35.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/f1/qj3m1q9507d2_7rnqwfgzyrm0000gp/T/pip-install-18svtd17/python-cdb_8f82bd43dc6740eca3362661cc4d7001/setup.py", line 25, in <module>
          ext_modules = [ Extension(
                          ^^^^^^^^^^
        File "/Users/glen/scm/delfi/api/pix-redirect-to-media-api-image-cropper/csv2cdb.py/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/extension.py", line 130, in __init__
          super().__init__(name, sources, *args, **kw)
        File "/Users/glen/scm/delfi/api/pix-redirect-to-media-api-image-cropper/csv2cdb.py/.direnv/python-3.11/lib/python3.11/site-packages/setuptools/_distutils/extension.py", line 110, in __init__
          raise AssertionError("'sources' must be a list of strings")
      AssertionError: 'sources' must be a list of strings
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


```

**Comment by merwok** [comment]
Yes: the setup script uses the `map` function to get a list of C source files, which returns a list in python 2 and a custom iterable in python 3.

This repo does not seem active, interested people could create a fork, address the issues and publish with a different name on PyPI.

**Comment by bbayles** [comment]
`pure-cdb` has a [python-cdn compatibility mode](https://python-pure-cdb.readthedocs.io/en/latest/compat.html), FWIW.
